version: '3'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_blog/
    ports:
      - "8000:8000"
    environment:
      - TEST_KEY

    stdin_open: true
    tty: true
